language: node_js
node_js:
  - 12 # uses version 12
services:
  - postgresql # starts up postgres
addons:
  postgresql: '9.6' # highest available postgres version on Travis
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
notifications:
  email:
    on_success: change # default: change (only when going from broken to fixed)
    on_failure: always # default: always (which is annoying, as it should be)
install:
  - npm ci # faster, goes only from package-lock
before_script:
  - psql -c 'create database "deployment-exercise-test";' -U postgres # remember to change this name if you change it elsewhere (e.g. package.json)
before_deploy: # omit node_modules, since we set skip_cleanup below
  - rm -rf node_modules
deploy: # see README for details on these keys
  # prevents travis from deleting the build
  skip_cleanup: true
  provider: heroku
  # app should be your heroku app name; see README
  app: still-eyrie-48007
  # the secure key indicates an encrypted value; see README
  api_key:
    secure: HYeOLkhtoslXzX2rP4ROdtk4YDgS89mxukUDGTPfpH4ZhAhLv79fv1vGyTSY0ZFD2p9tvqE/21JB3/JiTxo3Wp4FZt0oTmaxtVwjxpx7uyvuq+Sp2VUvDnjmGA4UpvSWRoaww/Dd9a+FPuI/8/zqfM4Lj4HVMTLtt65tAc1q/VKFQ7a+kB//4PQtetusqP3smiLDl6Fm/UQTPWVudPXRJM6r3dlgw47oM16j/Dn61SUXlu/Rf0sL3JZOgF3HN9kl7Gc1zFe9lL2wcRCqCiAg0tR1jV0I/1weWxtv2zBkjRbD0BG7uqK4IFOBbA3+BM1habHKW6uHLwLNdar6mFgTftkkwgRDyj7pBvtzXs7j75vEKwJLWT1oF987zjTX1MsW9mvyyLvgfl99tXJSIxnuo4zM0HVpvADduptB3CkerCiIsXGLkAMg0mXrxHYJmzPujLwrXlGSKoFvJEF4L7Iw0YGvn0vNtAO8Dz2zBKlzullwfWlVTXZTSbRbqkCxMcVcrJMUNDSBzfFc8EPUxopbv2SlzwDnRATzXQ4BBpA74VDUWPEzMe0kr7hQvkmS+ibewGVtnq3FMhquNiO/aSdE+sT7+uhpLHJJCjqeOGzArqNaE0/DDc1cy9DaobM5/uVeNI7ryiqK4en0OxsLCWw4ffLzTryJ9lQkTRD/5+/Zenc=
